### ISSUE TITLE
initial request from instrument scientist

### ISSUE THREAD

**Issue by prjemian** [aps-8id-trr/ipython-8idiuser#9]
> Getting back to Blue Sky, can we make a road map on transitioning 8-ID-I over the period of a cycle or so? To this end, knowing very limited to none of Blue Sky, we could live with the following minimum:
> 
> 1. Basic scanning capability (a(2)scan, d(2)scan, timescan)
> 2. Area detector integration, to the extent of commanding acquisition, basic file plugins, etc.
> 3. A lot of our metadata and data movement are already fully using Sinisa's DM and so we are in good shape w.r.t. python there.
> 
> Please let us know your thoughts.

* [x] basic scanning (Bluesky 101, #16)
* [x] Area detector integration (#11)
* [x] Area detector IMM plugin ( #24)
* [x] metadata and data movement (#25)

**Comment by prjemian** [comment]
Good list.

1. We have a conversion of SPEC's config file so motors and scalers are configured now.
1. a(2)scan is covered by bluesky's [`bp.scan`](https://blueskyproject.io/bluesky/generated/bluesky.plans.scan.html?highlight=scan#bluesky.plans.scan)
1. d(2)scan is covered by bluesky's [`bp.rel_scan`](https://blueskyproject.io/bluesky/generated/bluesky.plans.rel_scan.html?highlight=scan#bluesky.plans.rel_scan)
1. Bluesky's list of [standard plans](https://blueskyproject.io/bluesky/plans.html?highlight=scan#summary)
1. Area detector: we'll need more info about the PV and detector type to continue.  Should not be too much work.
1. We'll work out how to flow metadata from bluesky into Sinisa's system.  Good for us to get to this now.

**Comment by sureshnaps** [comment]
Responses:
1. spec config file -- no comments
2,3. a2,d2scans - good
4. ok
5. Lambda 750K:  screenshot attached
![Lambda_epics_screen](https://user-images.githubusercontent.com/3219523/61898271-8e9ae780-aede-11e9-8022-f26ebf33bcab.png)
It would be nice to be able to scan area detector during a bluesky scan

6. Regarding Sinisa's system, we will discuss before we work on it as I am doing some developments to aid this as well.

**Comment by prjemian** [comment]
here is the python file that writes the metadata using pvs written by spec to registers
/home/beams/8IDIUSER/Python_HDF5_DataExchange/Create_DataExchange_HDF5_8idi.py


spec macros that write to registers:
/home/beams/8IDIUSER/local_macros/CCD_macros/write_CCD_MetaData_hdf.mac

write_CCD_MetaData_hdf calls the python code to write hdf

**Comment by prjemian** [comment]
Data movement part is handled by the DM system using the 2 macros defined here:
/home/beams/8IDIUSER/local_macros/CCD_macros/DM_Workflow_macros.mac

**Comment by prjemian** [comment]
Copying these last two comments to issue #25 which tracks the metadata request

**Comment by prjemian** [comment]
Work is complete.
